version: "3.3"
services:
  traefik:
    image: traefik:v1.7
    command: --web \
      --docker \
      --docker.swarmmode \
      --docker.domain=omis.com \
      --docker.watch \
      --logLevel=DEBUG
    networks:
      - traefik-network
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role==manager]

  portainer:
    image: portainer/portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - traefik-network
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.port=9000"
        - "traefik.docker.network=mystack_traefik-network"
        - "traefik.frontend.rule=Host:portainer.omis.com"
  whoami:
    image: containous/whoami
    networks:
      - traefik-network
    deploy:
      replicas: 3
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.docker.network=mystack_traefik-network"
        - "traefik.frontend.rule=Host:whoami.omis.com"

networks:
  traefik-network:
    driver: overlay
